services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
    - .env.development
    ports:
    - 3000:3000
  proxy:
    image: hrk091/simple-proxy
    ports:
    - 8888:8888
    environment:
      TARGET_URL: https://event.cloudnativedays.jp/
